# -*- coding: utf-8 -*-
"""24-06-2021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KThk0ds1ykL-X9ebZylLbtxhks_1R66M
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

df = pd.read_csv('/content/hiring.csv')
df

df.isnull().sum()

df.info()

df['test_score'].fillna(df['test_score'].mean(), inplace=True)
df

df['experience'].fillna(0, inplace=True)
df

def string_to_num(word):
  dict = {'zero':0,'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6,'seven':7,
          'eight':8, 'nine':9, 'ten':10, 'eleven':11, 'twelve':12, 0:0}
  return dict[word]

df['experience'] = df['experience'].apply(lambda x: string_to_num(x))
df

x = df.iloc[:,:3]
y = df.iloc[:,-1]

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.1, random_state=5)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain, ytrain)

ypred = model.predict(xtest)

p=model.predict([[5,8,7]])
p

import pickle 
pickle.dump(model, open('model.pkl', 'wb'))